name: 버그 리포트
description: 발견한 버그 또는 오류를 보고
title: "[버그]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        날씨 메일 서비스에서 발견한 버그를 보고해 주셔서 감사합니다. 버그 수정에 도움이 될 수 있도록 아래 정보를 최대한 자세히 작성해 주세요.
  
  - type: dropdown
    id: component
    attributes:
      label: 영향받는 구성요소
      description: 이 버그가 영향을 미치는 구성요소를 선택해주세요.
      options:
        - 날씨 데이터 서비스 (weather_service)
        - 이메일 서비스 (email_service)
        - 스케줄러 (scheduler)
        - 로깅 (logging)
        - 메모리 관리 (memory_management)
        - 설정 (configuration)
        - 기타 (아래에 자세히 설명)
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: 버그 설명
      description: 발생한 버그에 대해 간결하고 명확하게 설명해 주세요.
      placeholder: 발생한 문제에 대해 설명해 주세요...
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: 재현 방법
      description: 버그를 재현하는 방법을 단계별로 설명해 주세요.
      placeholder: |
        1. '...' 명령어 실행
        2. '....' 설정 확인
        3. 오류 발생
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: 예상 동작
      description: 예상했던 동작은 무엇인가요?
      placeholder: 예상했던 동작 설명...
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: 로그 또는 오류 메시지
      description: 관련 로그나 오류 메시지를 붙여넣어 주세요.
      render: shell
      placeholder: 로그 또는 오류 메시지를 이곳에 붙여넣어 주세요.
  
  - type: input
    id: version
    attributes:
      label: 버전
      description: 사용 중인 날씨 메일 서비스 버전을 적어주세요.
      placeholder: 예) v1.0.0
    validations:
      required: false
  
  - type: textarea
    id: environment
    attributes:
      label: 환경 정보
      description: 운영 환경에 대한 정보를 제공해 주세요.
      placeholder: |
        - OS: [예) Ubuntu 20.04]
        - Python 버전: [예) 3.9.5]
        - 실행 환경: [예) Docker, Bare metal, etc.]
    validations:
      required: false
  
  - type: checkboxes
    id: terms
    attributes:
      label: 코드 규약
      description: 이슈를 제출하기 전에 다음 사항을 확인해 주세요.
      options:
        - label: 이미 존재하는 이슈인지 확인했습니다.
          required: true
        - label: 가능한 한 상세한 정보를 제공했습니다.
          required: true 