name: 성능 개선
description: 성능 개선 또는 최적화 제안
title: "[성능]: "
labels: ["performance", "optimization"]
body:
  - type: markdown
    attributes:
      value: |
        날씨 메일 서비스의 성능 개선을 위한 제안을 해주셔서 감사합니다. 아래 양식을 작성하여 개선점을 상세히 설명해 주세요.
  
  - type: dropdown
    id: component
    attributes:
      label: 관련 구성요소
      description: 성능 개선이 필요한 구성요소를 선택해주세요.
      options:
        - 날씨 데이터 서비스 (weather_service)
        - 이메일 서비스 (email_service)
        - 스케줄러 (scheduler)
        - 메모리 관리 (memory_management)
        - 비동기 처리 (async operations)
        - API 호출 (API requests)
        - 전체 시스템 (system-wide)
        - 기타 (아래에 자세히 설명)
    validations:
      required: true
  
  - type: textarea
    id: current_performance
    attributes:
      label: 현재 성능 상태
      description: 현재 성능 상태와 발견한 문제점을 설명해 주세요.
      placeholder: |
        - 느린 작업: [예) API 요청 처리]
        - 현재 시간/리소스 사용량: [예) 평균 요청 처리 시간 3초, 메모리 사용량 500MB]
        - 영향: [예) 높은 부하 시 시스템 응답 지연]
    validations:
      required: true
  
  - type: textarea
    id: improvement
    attributes:
      label: 개선 제안
      description: 어떻게 성능을 개선할 수 있을지 상세히 설명해 주세요.
      placeholder: 구체적인 개선 방법이나 알고리즘, 코드 변경 등을 제안해 주세요.
    validations:
      required: true
  
  - type: textarea
    id: expected_improvement
    attributes:
      label: 예상되는 개선 효과
      description: 제안하신 변경으로 예상되는 성능 개선 효과를 설명해 주세요.
      placeholder: |
        - 예상 시간/리소스 개선: [예) 요청 처리 시간 50% 감소, 메모리 사용량 30% 감소]
        - 기대 효과: [예) 시스템 안정성 향상, 사용자 경험 개선]
    validations:
      required: true
  
  - type: textarea
    id: measurement
    attributes:
      label: 성능 측정 방법
      description: 성능 개선을 측정할 수 있는 방법을 제안해 주세요.
      placeholder: |
        - 성능 지표: [예) 응답 시간, 처리량, 메모리 사용량]
        - 측정 도구: [예) cProfile, memory_profiler, 로그 분석]
        - 벤치마크 방법: [예) 100회 반복 테스트 후 평균 측정]
    validations:
      required: false
  
  - type: textarea
    id: code_example
    attributes:
      label: 코드 예시 (선택사항)
      description: 제안하신 개선 사항에 대한 코드 예시가 있다면 공유해 주세요.
      render: python
      placeholder: |
        # 개선 전 코드
        def original_function():
            # ...
            
        # 개선 후 코드
        def improved_function():
            # ...
    validations:
      required: false
  
  - type: checkboxes
    id: considerations
    attributes:
      label: 고려사항
      description: 성능 개선 제안에 관련된 다음 사항들을 고려해 주세요.
      options:
        - label: 이 변경이 시스템의 다른 부분에 영향을 줄 수 있습니다.
        - label: 이 변경은 테스트 케이스의 업데이트가 필요할 수 있습니다.
        - label: 이 개선은 추가적인 의존성을 도입합니다.
        - label: 이 개선은 구현의 복잡성을 증가시킬 수 있습니다.
  
  - type: checkboxes
    id: terms
    attributes:
      label: 코드 규약
      description: 이슈를 제출하기 전에 다음 사항을 확인해 주세요.
      options:
        - label: 이미 존재하는 이슈인지 확인했습니다.
          required: true
        - label: 실제 성능 문제에 대한 증거 또는 측정 결과가 있습니다.
          required: true 